name: Docker Image CI for GHCR
on:
  push
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Docker login
        run: |
          docker login --username takotori --password ${{ secrets.GH_PAT }} ghcr.io
      - name: Build and publish frontend
        run: |
          docker build frontend/ --tag ghcr.io/takotori/takotori-web-frontend:latest -f frontend/Dockerfile
          docker push ghcr.io/takotori/takotori-web-frontend:latest
      - name: Build and publish backend
        run: |
          docker build backend/ --tag ghcr.io/takotori/takotori-web-backend:latest -f backend/Dockerfile
          docker push ghcr.io/takotori/takotori-web-backend:latest
        with:
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max