name: Docker Image CI for GHCR
on:
  push:
    paths:
      - frontend/**
jobs:
  publishFrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: |
          docker login --username takotori --password ${{ secrets.GH_PAT }} ghcr.io
      - name: Build and publish frontend
        run: |
          docker build frontend/ --tag ghcr.io/takotori/takotori-web-frontend:latest -f frontend/Dockerfile
          docker push ghcr.io/takotori/takotori-web-frontend:latest
